In [1]:
import numpy as np

In [2]:
one_dimensional_array= np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [4]:
two_dimensional_array=np.array([[6, 5], [11,7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [5]:
sequence_of_integers=np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [9]:
random_integers_between_50_and_100=np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[78 52 57 58 88 51]


In [14]:
random_floats_between_0_and_1=np.random.random([6])
print(random_floats_between_0_and_1)

[0.79937908 0.16083559 0.51780227 0.7302468  0.96502921 0.43826516]


In [15]:
random_floats_between_2_and_3=random_floats_between_0_and_1 +2.0
print(random_floats_between_2_and_3)

[2.79937908 2.16083559 2.51780227 2.7302468  2.96502921 2.43826516]


In [17]:
random_integers_between_150_and_300= random_integers_between_50_and_100*3
print(random_integers_between_150_and_300)

[234 156 171 174 264 153]


In [20]:
#Create a Linear Dataset
feature= np.arange(6, 21)
print(feature)

label= (feature*3)+4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
noise = (np.random.random([15])*4)
print(noise)
label=label+noise